id: A967B4F64
title: 'Eliminator of All Delusory Perception: A Prayer to Guru Dewa Chenpo, the Guru
  of Great Bliss'
type: translation
pechas:
- I1C7DEB8D
- I463B6B56
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:11:14.806119
  last_modified_at: 2023-01-04 12:11:14.806126
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I1C7DEB8D/4DE9: '6616'
  I463B6B56/BB2F: '6616'
